### PR TITLE
Upgrade to OpenSAML v5

### PR DESCRIPTION
**Pull request by mmoayyed**
OpenSAML v4 will no longer be maintained, and v5 should be released in 1-2 months. This PR prepares the project to catch up to OS v5, possibly in line with the v3 release.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Hello @coheigea is this something that can be included in v4 here? Given OpenSAML v5 does provide support for Jakarta APIs?

**Comment by coheigea** [comment]
Hi @mmoayyed , I think this would require a new version of WSS4J, either 3.1.0 or 4.0.0 due to the requirement to use Java 17. But I'm open to a release for sure, once OpenSAML 5.0.0 is released.

**Comment by mmoayyed** [comment]
I appreciate your update. I am keeping an eye out for the OS release, and will post back here. (Anticipating late December)

**Comment by mmoayyed** [comment]
@coheigea Small question if I may: I see that v3 release supports jakarta APIs, and yet the release is still based on OpenSAML v4 which has no support for such APIs. Would't this mean that SAML functionality is effectively broken in the v3 release?

**Comment by coheigea** [comment]
@mmoayyed Not that I can see, all tests using SAML pass in both WSS4J and CXF 4.0.0.

**Comment by mmoayyed** [comment]
Ok thank you. I am guessing that is likely because wss4j is not using any of the opensaml encoders/decoders that wants to deal with http request and or response(?) since they mainly belong to the javax/jakarta namespace. Otherwise I am not sure how this could ever work :)

**Comment by coheigea** [comment]
Any ETA on getting opensaml5 released?

**Comment by mmoayyed** [comment]
No news yet. It generally should happen along with the release of the shibboleth idp v5, and I suspect that might happen in approx a month. Certainly in Q1. Fingers crossed. 

How do you feel about merging this and letting folks test changes? At the moment I have a custom fork of the project here built against opensaml v5 and released via GitHub so we can run integration tests. There should hopefully not be any major compatibility issues.

**Comment by mmoayyed** [comment]
Update on OpenSAML v5: 

9/4 - code freeze modulo bug fixes
9/11﻿ - release process over this week

**Comment by mmoayyed** [comment]
V5 is now released. Shall I update this pull request?

**Comment by coheigea** [comment]
Please do @mmoayyed

**Comment by mmoayyed** [comment]
This is now done, and I suppose GH workflows should also update to support JDK 17 which is the minimum requirement for OS v5.

**Comment by coheigea** [comment]
@mmoayyed Thanks, can you rebase this off the latest master? I bumped the version to 4.0.0-SNAPSHOT and Java 17. I bumped also to XML Security 4.0.0-SNAPSHOT, I hope this doesn't clash with what OpenSAML uses...

**Comment by mmoayyed** [comment]
There now exists:

```
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.049 s <<< FAILURE! -- in org.apache.wss4j.dom.saml.SamlNegativeTest
Error:  org.apache.wss4j.dom.saml.SamlNegativeTest.testSAML2AuthnAssertionModified -- Time elapsed: 0.010 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at org.apache.wss4j.dom.saml.SamlNegativeTest.testSAML2AuthnAssertionModified(SamlNegativeTest.java:149)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Is this something you'd like me to look into?

**Comment by coheigea** [comment]
@mmoayyed What error code is being returned instead for this test?

**Comment by coheigea** [comment]
I've fixed the test on master, can you rebase again please?

**Review by coheigea — APPROVED** [review]

**Pull request merged**
