### PR TITLE
[WSS-662] [OSGi] Support for SAAJ-RI 1.4.0

### PR DESCRIPTION
**Pull request by amarkevich**

### CODE REVIEW

**Comment by coheigea** [comment]
How are you testing this? If I change CXF master to use <cxf.saaj-impl.bundle.version>1.4.0_2</cxf.saaj-impl.bundle.version>, then I get errors in the OSGi STS systests.

**Comment by amarkevich** [comment]
I put changes to https://github.com/apache/cxf/commits/saaj-impl
The OSGi STS systests is only affected

**Comment by amarkevich** [comment]
CXF branch updated and OSGi STS systests passed using this changes

**Comment by coheigea** [comment]
@amarkevich Is this PR still needed?

**Comment by amarkevich** [comment]
its prerequisite for https://github.com/apache/cxf/tree/saaj-impl and don't break existing functionality

**Pull request merged**
