### PR TITLE
WSS-693 Fail build if CVSS score is above 6

### PR DESCRIPTION
**Pull request by free2create**
Ignore findings by editing build-tools/dependency-check-suppression.xml and adding checksum of jar File.

* Remove unneeded profile for dependency check since it is not optional anymore.
* trim dep management to just version info.

### CODE REVIEW

**Comment by free2create** [comment]
@coheigea any feedback ?

**Review by coheigea — COMMENTED** [review]
The problem is I tried in this morning and got:

[ERROR] 	UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
[ERROR] 		caused by DownloadFailedException: Download failed, unable to retrieve 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta'; Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta; unable to connect.
[ERROR] 		caused by DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta; unable to connect.
[ERROR] 		caused by SocketTimeoutException: connect timed out
[ERROR] 	NoDataException: No documents exist

So I think maybe it's safer not to block the build and have it in a profile as before?

**Comment by free2create** [comment]
Are you using this behind a firewall? 

When I added this for a application  behind a firewall that normally used a Nexus as a mirror for maven central we added a proxy configuration in the settings file. You tell the proxy that you still want to continue to use Nexus as a mirror, but all other traffic should go through the proxy. 

Anyway I will move this back to a profile and  update the Apache CI to use the profile does that sound like a plan ?

**Comment by coheigea** [comment]
Thanks, that sounds good.

**Comment by free2create** [comment]
FYI
There is some maven lifecycle strangeness that is happening when this is moved to a profile that I am trying to figure out. 
A 'mvn deploy' , is not triggering the plugin even when I pin this the _compile_ or _verify_ lifecycle. I even added _verify_ to the release plugings preparationGoals.

**Comment by free2create** [comment]
@coheigea  I was lazy and created this change in my fork master, I am going to close, blow away fork and recreate so I can look at build error for OpenSaml https://github.com/apache/ws-wss4j/pull/49

**Pull request closed without merging**
