### PR TITLE
upgrade Felix maven-bundle-plugin to 5.1.3

### PR DESCRIPTION
**Pull request by hboutemy**
fixes Reproducible Builds issues

### CODE REVIEW

**Comment by veithen** [comment]
Note that with this change, the bundle manifests still have a `Bnd-LastModified` header, i.e. the build is not deterministic/reproducible. Is this expected?

**Comment by hboutemy** [comment]
uh, how is it possible?
I added an IT in maven-bundle-plugin 5.1.3 to check that it does not happen:
- https://github.com/apache/felix-dev/commit/be537033353c575a33d85a8653a0df056b54bfa2
- https://github.com/apache/felix-dev/commit/957e5c9838aa67061888760286cb78251bee50bd

**Comment by hboutemy** [comment]
just tested: with default packaging (default to `jar`), yes, there is the `Bnd-LastModified` header
but using `<packaging>bundle</packaging>`, it disappears (as expected)

is there a reason to not use `bundle` packaging?

**Comment by veithen** [comment]
They actually used to have `bundle` packaging, but that was changed in https://github.com/apache/ws-wss4j/commit/9a3bcc1a4b0d685e53a8b1a5b121df1b4a371e71. The commit description doesn't explain why that was done though. Maybe @dkulp remembers? Also, it looks like there are no tests that validate that the bundles work properly, so changes are risky.

**Comment by hboutemy** [comment]
bug reported to Felix and PR provided: https://issues.apache.org/jira/browse/FELIX-6495

we'll need to wait for 5.1.4 to have a fixed bundle:manifest goal

**Comment by veithen** [comment]
Looks like maven-bundle-plugin 5.1.4 fixes that problem.

**Comment by hboutemy** [comment]
@veithen FYI, wss4j 3.0.0 is confirmed fully reproducible: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/wss4j/README.md

**Pull request closed without merging**
