### PR TITLE
Update for support of the ED448 and ED25519 keys and signatures

### PR DESCRIPTION
**Pull request by jrihtarsic**
The PR includes small updated and basic tests  to support EdEC keys for ED448 and ED25519 signatures which are already supported by the xmlsec library.

### CODE REVIEW

**Comment by coheigea** [comment]
@jrihtarsic Can you rebase this off master as well please?

**Comment by jrihtarsic** [comment]
@coheigea  I will do that now and I will close this ticket. Should I create also the JIRA ticket for adding the  "eddsa-signature feature" to WSS4J or the PR is sufficient?

**Comment by coheigea** [comment]
A JIRA would be great as well, thanks @jrihtarsic

**Comment by jrihtarsic** [comment]
This PR was closed because a new PR [260](https://github.com/apache/ws-wss4j/pull/260) addresses this request on main/master branch.

**Pull request closed without merging**
